jakarta.persistence.jdbc.url=mongodb://localhost/mongo-hibernate-test?directConnection=false
hibernate.query.plan_cache_enabled=false #make tests more isolated from each other
com.mongodb.hibernate.semantics.nulls=MQL
jakarta.persistence.schema-generation.database.action=create-drop
com.mongodb.hibernate.schema.validation=true
hibernate.hbm2ddl.halt_on_error=true